name: branch workflow

run-name: branch workflow
on: 
  pull_request:
   branches:
     - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: issues step
        shell: bash
        run: echo "issues workflow successfull"
